第十章 调 试
程序员之间流传着一个老笑话：“编码占了编程工作量的90%，调试占了另外90%。”
10.1 抛出异常
当Python 试图执行无效代码时，就会抛出异常。在第 3 章中，你已看到如何使用try 和except 语句来处理Python 的异常，这样程序就可以从你预期的异常中恢复。
但你也可以在代码中抛出自己的异常。抛出异常相当于是说：“停止运行这个函数中的代码，将程序执行转到except 语句”。

抛出异常使用raise 语句。在代码中，raise 语句包含以下部分：
? raise 关键字；
? 对Exception 函数的调用；
? 传递给Exception 函数的字符串，包含有用的出错信息。